name: Build Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v4

      - name: Install Android SDK 36
        run: sdkmanager "platforms;android-36" "build-tools;36.0.0"

      - name: Extract project
        run: |
          mkdir android-project
          unzip -q "1001-Istilohi-Iqtisodi-Android.zip" -d android-project

      - name: Build Android App
        working-directory: android-project/1001-Istilohi-Iqtisodi-Android
        run: |
          chmod +x gradlew
          ./gradlew --no-daemon assembleDebug bundleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: 1001-Istilohi-Iqtisodi-APK
          path: android-project/1001-Istilohi-Iqtisodi-Android/app/build/outputs/apk/debug/*.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: 1001-Istilohi-Iqtisodi-AAB
          path: android-project/1001-Istilohi-Iqtisodi-Android/app/build/outputs/bundle/release/*.aab
